#
# board/renesas/alt/Makefile
#
# Copyright (C) 2014 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0
#

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= alt_spl.o
else
obj-y	:= alt.o qos.o
endif
