#
# Copyright (C) 2017, DENX Software Engineering
# Lukasz Majewski <lukma@denx.de>
#
# SPDX-License-Identifier:    GPL-2.0+
#
ifeq ($(CONFIG_SPL_BUILD),y)
obj-y = spl.o
else
obj-y := display5.o
endif
