# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2016-2017
# Lukasz Majewski, DENX Software Engineering, lukma@denx.de
ifeq ($(CONFIG_SPL_BUILD),y)
obj-y  := spl.o
else
obj-y  := mccmon6.o
endif
