#
# board/renesas/lager/Makefile
#
# Copyright (C) 2013 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0
#

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= lager_spl.o
else
obj-y	:= lager.o qos.o
endif
