# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= spl.o
else
obj-y	:= mx6memcal.o
endif
