#
# board/renesas/koelsch/Makefile
#
# Copyright (C) 2013 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0
#

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= koelsch_spl.o
else
obj-y	:= koelsch.o qos.o
endif
