# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

ifeq ($(CONFIG_SPL_BUILD),y)
obj-y	:= spl.o common.o
else
obj-y	:= igep00x0.o common.o
endif
